pub mod sim;
mod planet;
mod plate;
mod plate_generator;
mod vary;
mod rock_store;
mod helpers;
pub mod sim_manager;
mod h3o_utils;
mod geoconverter;
mod thermal_plate_generator;
mod asthenosphere;
mod asth_sim;
mod cool_asth_cell;
mod asth_constants;
pub mod gif_exporter;
pub mod png_exporter;
mod level_cells;